language: php

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_ROUTING_VERSION=4.1.*
  - SYMFONY_ROUTING_VERSION=4.2.*

before_script:
  - composer require "symfony/routing:${SYMFONY_ROUTING_VERSION}" --no-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml